// <auto-generated />
namespace PoS.Dal.Sql.Ctx.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _0001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_0001));
        
        string IMigrationMetadata.Id
        {
            get { return "201802122240222_0.001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
